### PR TITLE
perf: use bitwise operations in add/sub impls

### PR DESCRIPTION
**Pull request by DaniPopes**
See https://github.com/rust-lang/rust/issues/85532#issuecomment-2495119815

### CODE REVIEW

**Comment by prestwich** [comment]
CI failure caused by this:
https://github.com/paritytech/parity-scale-codec/issues/662

**Review by prestwich — APPROVED** [review]

**Comment by prestwich** [comment]
gonna hold this open a couple days to see if parity will patch

**Comment by recmo** [comment]
Is there a perf difference between using `|` and `||` on a `bool`?

**Comment by recmo** [comment]
Ah, looks like there is some issue. Rustc has a similar patch: https://github.com/rust-lang/rust/commit/9836196e3cca6661e752c3acd8bc207f181736ed

**Comment by prestwich** [comment]
parity has yanked parity-scale-codec@3.7.0 and CI is passing so this is good to go

**Pull request merged**
