### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by kpp**
Update deps.

### CODE REVIEW

**Comment by prestwich** [comment]
wrt optional deps, our semver policy treats breaking changes as semver major. We typically update by adding support for specific versions (see #403 and the discussion in #404).  If you have a need for support for these crates at specific versions we can add those versions to the support directory, but modifying (removing) the existing support is a no go from our side

**Comment by kpp** [comment]
Can you help me with that? I wanted to update deps to reduce the number of outdated deps in my project.

If I want to update `primitive-types`, `rlp` and `ethereum_ssz`, I have to add new features for those updated deps?

**Comment by prestwich** [comment]
> Can you help me with that? I wanted to update deps to reduce the number of outdated deps in my project.

I think that #403 is a pretty good roadmap for achieving that. The basic steps are
- add the new dependency with version number in name (renaming the old one to include a version number too)
- add the new file to `support/`
- edit the existing support to use the renamed version of the old package
- do NOT edit the feature name

**Comment by prestwich** [comment]
in the meantime, i'm closing this as `wontfix` as this PR would violate our semver policies. would love to see followup PRs tho :)

**Pull request closed without merging**
